# Generated by Django 5.2.12 on 2026-03-31 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('code_annee', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lib_annee', models.CharField(blank=True, max_length=45, null=True)),
                ('obs_annee', models.CharField(blank=True, max_length=45, null=True)),
                ('date_deb', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'annee',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('EXPORT', 'Export')], max_length=20)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.CharField(blank=True, max_length=50, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('code_bat', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('lib_bat', models.CharField(blank=True, max_length=25, null=True)),
                ('obs_bat', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'batiment',
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('code_cycle', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lib_cycle', models.CharField(max_length=45)),
                ('obs_cycle', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cycle',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('code_dep', models.CharField(db_column='Code_dep', max_length=10, primary_key=True, serialize=False)),
                ('lib_dep', models.CharField(max_length=100)),
                ('obs_dep', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'departement',
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('code_etab', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lib_etab', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=45, null=True)),
                ('tel', models.CharField(blank=True, max_length=30, null=True)),
                ('fax', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('siteweb', models.CharField(blank=True, db_column='Siteweb', max_length=100, null=True)),
            ],
            options={
                'db_table': 'etablissement',
            },
        ),
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('code_jour', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lib_jour', models.CharField(max_length=15)),
                ('obs_jour', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'jour',
            },
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('code_langue', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('lib_langue', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'langue',
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('code_mention', models.AutoField(primary_key=True, serialize=False)),
                ('lib_mention', models.CharField(max_length=15)),
                ('note_min', models.PositiveIntegerField(default=0)),
                ('note_max', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'mention',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code_module', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lib_module', models.CharField(max_length=25)),
                ('obs_module', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('code_pension', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('lib_pension', models.CharField(blank=True, max_length=25, null=True)),
                ('mt_pension', models.FloatField(default=0)),
                ('obs_pension', models.CharField(blank=True, max_length=45, null=True)),
                ('nb_tranche', models.PositiveIntegerField(blank=True, null=True)),
                ('mt_inscription', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'pension',
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('code_rapport', models.AutoField(primary_key=True, serialize=False)),
                ('lib_rapport', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'rapport',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('code_salle', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('lib_salle', models.CharField(blank=True, max_length=15, null=True)),
                ('obs_salle', models.CharField(default='', max_length=45)),
            ],
            options={
                'db_table': 'salle',
            },
        ),
        migrations.CreateModel(
            name='TypeEtab',
            fields=[
                ('code_type', models.AutoField(primary_key=True, serialize=False)),
                ('lib_type', models.CharField(blank=True, max_length=25, null=True)),
                ('obs_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'type_etab',
            },
        ),
        migrations.CreateModel(
            name='TypeEvaluation',
            fields=[
                ('code_type_eval', models.AutoField(db_column='code_typeEval', primary_key=True, serialize=False)),
                ('lib_type_eval', models.CharField(max_length=20)),
                ('obs_type_eval', models.CharField(blank=True, db_column='obs_typeEval', max_length=45, null=True)),
            ],
            options={
                'db_table': 'type_evaluation',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('login', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=20)),
                ('nom_user', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(default='USER', max_length=20)),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('code_classe', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lib_classe', models.CharField(max_length=25)),
                ('obs_classe', models.CharField(blank=True, max_length=45, null=True)),
                ('code_niveau', models.CharField(blank=True, max_length=5, null=True)),
                ('code_bat', models.CharField(blank=True, max_length=5, null=True)),
                ('code_salle', models.CharField(blank=True, max_length=5, null=True)),
                ('eff_max', models.PositiveIntegerField(db_column='EffMax', default=50)),
                ('code_spec', models.CharField(blank=True, db_column='Code_Spec', max_length=10, null=True)),
                ('code_dep', models.ForeignKey(blank=True, db_column='code_dep', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.departement')),
            ],
            options={
                'db_table': 'classe',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('mle_ens', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_ens', models.CharField(max_length=25)),
                ('prenom_ens', models.CharField(blank=True, max_length=25, null=True)),
                ('adresse_ens', models.CharField(blank=True, max_length=45, null=True)),
                ('tel_ens', models.CharField(blank=True, max_length=30, null=True)),
                ('email_ens', models.CharField(blank=True, max_length=45, null=True)),
                ('statut', models.CharField(blank=True, max_length=15, null=True)),
                ('code_dep', models.ForeignKey(blank=True, db_column='code_dep', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.departement')),
            ],
            options={
                'db_table': 'enseignant',
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='code_etab',
            field=models.ForeignKey(blank=True, db_column='code_etab', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.etablissement'),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('mle_etudiant', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=45)),
                ('prenom', models.CharField(blank=True, max_length=45, null=True)),
                ('date_naiss', models.DateTimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=25, null=True)),
                ('region_or', models.CharField(blank=True, max_length=25, null=True)),
                ('nom_pere', models.CharField(blank=True, max_length=45, null=True)),
                ('nom_mere', models.CharField(blank=True, max_length=45, null=True)),
                ('adresse', models.CharField(blank=True, max_length=45, null=True)),
                ('tel', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('domicile', models.CharField(blank=True, max_length=45, null=True)),
                ('nom_tuteur', models.CharField(db_column='Nom_tuteur', max_length=45)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('chemin', models.CharField(blank=True, max_length=254, null=True)),
                ('code_dep', models.ForeignKey(blank=True, db_column='code_dep', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.departement')),
            ],
            options={
                'db_table': 'etudiant',
            },
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('code_frais', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('lib_frais', models.CharField(max_length=30)),
                ('obs_frais', models.CharField(blank=True, max_length=45, null=True)),
                ('type_frais', models.CharField(max_length=25)),
                ('mt_frais', models.FloatField(default=0)),
                ('code_annee', models.ForeignKey(blank=True, db_column='code_annee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.annee')),
            ],
            options={
                'db_table': 'frais',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('code_inscription', models.AutoField(primary_key=True, serialize=False)),
                ('date_inscription', models.DateTimeField(blank=True, null=True)),
                ('mt_inscription', models.PositiveIntegerField(default=0)),
                ('code_annee', models.ForeignKey(db_column='code_annee', on_delete=django.db.models.deletion.CASCADE, to='api.annee')),
                ('code_classe', models.ForeignKey(db_column='code_classe', on_delete=django.db.models.deletion.CASCADE, to='api.classe')),
                ('mle_etudiant', models.ForeignKey(db_column='mle_etudiant', on_delete=django.db.models.deletion.CASCADE, to='api.etudiant')),
            ],
            options={
                'db_table': 'inscription',
            },
        ),
        migrations.CreateModel(
            name='FraisInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_frais', models.DateTimeField(blank=True, null=True)),
                ('code_frais', models.ForeignKey(db_column='code_frais', on_delete=django.db.models.deletion.CASCADE, to='api.frais')),
                ('code_inscription', models.ForeignKey(db_column='code_inscription', on_delete=django.db.models.deletion.CASCADE, to='api.inscription')),
            ],
            options={
                'db_table': 'frais_inscription',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('code_matiere', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lib_matiere', models.CharField(max_length=25)),
                ('obs_matiere', models.CharField(blank=True, db_column='Obs_matiere', max_length=45, null=True)),
                ('code_module', models.ForeignKey(db_column='Code_module', on_delete=django.db.models.deletion.RESTRICT, to='api.module')),
            ],
            options={
                'db_table': 'matiere',
            },
        ),
        migrations.CreateModel(
            name='Moratoire',
            fields=[
                ('code_mor', models.AutoField(primary_key=True, serialize=False)),
                ('lib_mor', models.CharField(blank=True, max_length=45, null=True)),
                ('date_exp', models.DateTimeField(blank=True, null=True)),
                ('date_effet', models.DateTimeField(blank=True, null=True)),
                ('mle_etudiant', models.ForeignKey(db_column='mle_etudiant', on_delete=django.db.models.deletion.RESTRICT, to='api.etudiant')),
            ],
            options={
                'db_table': 'moratoire',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('code_niveau', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('lib_niveau', models.CharField(max_length=25)),
                ('obs_niveau', models.CharField(blank=True, max_length=45, null=True)),
                ('code_pension', models.PositiveIntegerField(blank=True, null=True)),
                ('code_annee', models.ForeignKey(blank=True, db_column='code_annee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.annee')),
                ('code_cycle', models.ForeignKey(blank=True, db_column='code_cycle', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cycle')),
            ],
            options={
                'db_table': 'niveau',
            },
        ),
        migrations.AddField(
            model_name='cycle',
            name='code_pension',
            field=models.ForeignKey(blank=True, db_column='Code_pension', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pension'),
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('code_periode', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('lib_periode', models.CharField(max_length=20)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('obs_periode', models.CharField(blank=True, max_length=45, null=True)),
                ('code_annee', models.ForeignKey(blank=True, db_column='code_annee', null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.annee')),
            ],
            options={
                'db_table': 'periode',
            },
        ),
        migrations.CreateModel(
            name='RapportCours',
            fields=[
                ('code_lgnrapport', models.AutoField(primary_key=True, serialize=False)),
                ('detail_rapport', models.CharField(max_length=45)),
                ('code_classe', models.ForeignKey(db_column='code_classe', on_delete=django.db.models.deletion.RESTRICT, to='api.classe')),
                ('code_matiere', models.ForeignKey(db_column='code_matiere', on_delete=django.db.models.deletion.RESTRICT, to='api.matiere')),
                ('code_rapport', models.ForeignKey(db_column='code_rapport', on_delete=django.db.models.deletion.RESTRICT, to='api.rapport')),
                ('mle_ens', models.ForeignKey(db_column='mle_ens', on_delete=django.db.models.deletion.RESTRICT, to='api.enseignant')),
            ],
            options={
                'db_table': 'rapport_cours',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('code_sp', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lib_sp', models.CharField(max_length=45)),
                ('obs_sp', models.CharField(blank=True, max_length=45, null=True)),
                ('code_dep', models.ForeignKey(db_column='code_dep', on_delete=django.db.models.deletion.RESTRICT, to='api.departement')),
            ],
            options={
                'db_table': 'specialite',
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='code_sp',
            field=models.ForeignKey(blank=True, db_column='code_sp', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.specialite'),
        ),
        migrations.CreateModel(
            name='Tranche',
            fields=[
                ('code_tranche', models.AutoField(primary_key=True, serialize=False)),
                ('lib_tranche', models.CharField(max_length=10)),
                ('obs_tranche', models.CharField(blank=True, max_length=45, null=True)),
                ('mt_tranche', models.PositiveIntegerField(default=0)),
                ('code_pension', models.ForeignKey(db_column='code_pension', on_delete=django.db.models.deletion.RESTRICT, to='api.pension')),
            ],
            options={
                'db_table': 'tranche',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('code_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('mt_paiement', models.PositiveIntegerField(default=0)),
                ('obs_paiement', models.CharField(default='', max_length=45)),
                ('code_annee', models.ForeignKey(db_column='code_annee', on_delete=django.db.models.deletion.RESTRICT, to='api.annee')),
                ('mle_etudiant', models.ForeignKey(db_column='mle_etudiant', on_delete=django.db.models.deletion.RESTRICT, to='api.etudiant')),
                ('code_tranche', models.ForeignKey(db_column='code_tranche', on_delete=django.db.models.deletion.RESTRICT, to='api.tranche')),
            ],
            options={
                'db_table': 'paiement',
            },
        ),
        migrations.AddField(
            model_name='etablissement',
            name='code_type',
            field=models.ForeignKey(db_column='code_type', on_delete=django.db.models.deletion.CASCADE, to='api.typeetab'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('code_eval', models.AutoField(primary_key=True, serialize=False)),
                ('date_eval', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(max_length=10)),
                ('obs_eval', models.CharField(blank=True, max_length=45, null=True)),
                ('code_classe', models.ForeignKey(db_column='code_classe', on_delete=django.db.models.deletion.CASCADE, to='api.classe')),
                ('mle_etudiant', models.ForeignKey(db_column='mle_etudiant', on_delete=django.db.models.deletion.CASCADE, to='api.etudiant')),
                ('code_matiere', models.ForeignKey(db_column='code_matiere', on_delete=django.db.models.deletion.CASCADE, to='api.matiere')),
                ('code_periode', models.ForeignKey(db_column='code_periode', on_delete=django.db.models.deletion.CASCADE, to='api.periode')),
                ('code_type_eval', models.ForeignKey(db_column='code_typeEval', on_delete=django.db.models.deletion.CASCADE, to='api.typeevaluation')),
            ],
            options={
                'db_table': 'evaluation',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mle_ens', models.CharField(max_length=10)),
                ('h_debut', models.DateTimeField(blank=True, null=True)),
                ('date_cours', models.DateTimeField(blank=True, null=True)),
                ('code_classe', models.ForeignKey(db_column='code_classe', on_delete=django.db.models.deletion.CASCADE, to='api.classe')),
                ('code_matiere', models.ForeignKey(db_column='code_matiere', on_delete=django.db.models.deletion.RESTRICT, to='api.matiere')),
            ],
            options={
                'db_table': 'cours',
                'unique_together': {('code_matiere', 'code_classe')},
            },
        ),
        migrations.CreateModel(
            name='MentionClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_mention', models.CharField(default='', max_length=45)),
                ('code_classe', models.ForeignKey(db_column='code_classe', on_delete=django.db.models.deletion.RESTRICT, to='api.classe')),
                ('code_mention', models.ForeignKey(db_column='code_mention', on_delete=django.db.models.deletion.RESTRICT, to='api.mention')),
            ],
            options={
                'db_table': 'mention_classe',
                'unique_together': {('code_classe', 'code_mention')},
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_h', models.PositiveIntegerField(db_column='nbH', default=0)),
                ('code_annee', models.CharField(max_length=10)),
                ('code_classe', models.ForeignKey(db_column='code_classe', on_delete=django.db.models.deletion.RESTRICT, to='api.classe')),
                ('code_jour', models.ForeignKey(db_column='code_jour', on_delete=django.db.models.deletion.RESTRICT, to='api.jour')),
                ('code_matiere', models.ForeignKey(db_column='code_matiere', on_delete=django.db.models.deletion.RESTRICT, to='api.matiere')),
                ('mle_ens', models.ForeignKey(db_column='mle_ens', on_delete=django.db.models.deletion.RESTRICT, to='api.enseignant')),
            ],
            options={
                'db_table': 'planning',
                'unique_together': {('code_matiere', 'code_classe', 'code_jour', 'mle_ens')},
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_qual', models.CharField(blank=True, max_length=45, null=True)),
                ('code_matiere', models.ForeignKey(db_column='code_matiere', on_delete=django.db.models.deletion.RESTRICT, to='api.matiere')),
                ('mle_ens', models.ForeignKey(db_column='mle_ens', on_delete=django.db.models.deletion.RESTRICT, to='api.enseignant')),
            ],
            options={
                'db_table': 'qualification',
                'unique_together': {('code_matiere', 'mle_ens')},
            },
        ),
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coef', models.PositiveIntegerField(default=0)),
                ('duree_eval', models.PositiveIntegerField(default=0)),
                ('nbh_total', models.PositiveIntegerField(default=0)),
                ('note_elim', models.PositiveIntegerField(blank=True, null=True)),
                ('code_annee', models.ForeignKey(db_column='code_annee', on_delete=django.db.models.deletion.RESTRICT, to='api.annee')),
                ('code_classe', models.ForeignKey(db_column='code_classe', on_delete=django.db.models.deletion.CASCADE, to='api.classe')),
                ('code_matiere', models.ForeignKey(db_column='code_matiere', on_delete=django.db.models.deletion.RESTRICT, to='api.matiere')),
                ('mle_ens', models.ForeignKey(db_column='mle_ens', on_delete=django.db.models.deletion.RESTRICT, to='api.enseignant')),
            ],
            options={
                'db_table': 'unite_enseignement',
                'unique_together': {('code_matiere', 'code_classe')},
            },
        ),
    ]
