# Generated by Django 5.2.12 on 2026-04-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-date_action'], 'verbose_name': "Journal d'audit", 'verbose_name_plural': "Journal d'audit"},
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='created_at',
            new_name='date_action',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='new_values',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='old_values',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='record_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='table_name',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user_login',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='modele',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='objet_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='utilisateur',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(blank=True, default='PAYE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Connexion réussie'), ('LOGIN_FAILED', 'Échec de connexion'), ('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('BULK_DELETE', 'Suppression multiple'), ('EXPORT_CSV', 'Export CSV'), ('LOGOUT', 'Déconnexion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='passwd',
            field=models.CharField(max_length=128),
        ),
    ]
