# Generated by Django 5.2.12 on 2026-07-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_departement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['login']},
        ),
    ]
