# Generated by Django 5.2.12 on 2026-08-07 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeevaluation',
            name='ponderation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Pourcentage de ce type d'évaluation dans la moyenne de la période (ex: 30.00 pour 30%).", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
