# Generated by Django 5.2.12 on 2026-04-20 11:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rapportfinancier_rapportstatistique_tuteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteetudiant',
            name='code_annee',
            field=models.ForeignKey(db_column='code_annee', on_delete=django.db.models.deletion.RESTRICT, to='api.annee'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='code_dep',
            field=models.ForeignKey(blank=True, db_column='code_dep', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.departement'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='note',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='facture',
            name='code_annee',
            field=models.ForeignKey(db_column='code_annee', on_delete=django.db.models.deletion.RESTRICT, to='api.annee'),
        ),
        migrations.AlterField(
            model_name='fichenotes',
            name='code_annee',
            field=models.ForeignKey(db_column='code_annee', on_delete=django.db.models.deletion.RESTRICT, to='api.annee'),
        ),
        migrations.AlterField(
            model_name='lettreadmission',
            name='code_annee',
            field=models.ForeignKey(db_column='code_annee', on_delete=django.db.models.deletion.RESTRICT, to='api.annee'),
        ),
        migrations.AlterField(
            model_name='rapportfinancier',
            name='code_annee',
            field=models.ForeignKey(db_column='code_annee', on_delete=django.db.models.deletion.RESTRICT, to='api.annee'),
        ),
        migrations.AlterField(
            model_name='rapportstatistique',
            name='code_annee',
            field=models.ForeignKey(db_column='code_annee', on_delete=django.db.models.deletion.RESTRICT, to='api.annee'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='code_annee',
            field=models.ForeignKey(db_column='code_annee', on_delete=django.db.models.deletion.RESTRICT, to='api.annee'),
        ),
    ]
