# Generated by Django 5.2.12 on 2026-04-26 07:47
# Patched: SeparateDatabaseAndState used for operations already applied to DB.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_carteetudiant_code_annee_and_more'),
    ]

    operations = [

        # ── Colonnes / contraintes déjà présentes en base ─────────────────────
        # decision: l'ancienne unique_together (mle_etudiant, code_annee) n'a
        # jamais existé en base → on met à jour l'état Django uniquement.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='decision',
                    unique_together=set(),
                ),
            ],
        ),
        # decision.session : colonne déjà présente en base.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='decision',
                    name='session',
                    field=models.CharField(
                        choices=[('NORMALE', 'Session normale'), ('RATTRAPAGE', 'Session de rattrapage')],
                        default='NORMALE',
                        max_length=15,
                    ),
                ),
            ],
        ),
        # decision: nouvelle unique_together déjà présente en base.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='decision',
                    unique_together={('mle_etudiant', 'code_annee', 'session')},
                ),
            ],
        ),

        # diplome.type_diplome : colonne déjà présente en base.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='diplome',
                    name='type_diplome',
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ('LICENCE', 'Licence'),
                            ('LICENCE_PRO', 'Licence Professionnelle'),
                            ('MASTER', 'Master'),
                            ('MASTER_PRO', 'Master Professionnel'),
                            ('DOCTORAT', 'Doctorat / PhD'),
                            ('BTS', 'Brevet de Technicien Supérieur'),
                            ('HND', 'Higher National Diploma'),
                            ('DUT', 'Diplôme Universitaire de Technologie'),
                            ('INGENIEUR', "Diplôme d'Ingénieur"),
                            ('DEA', 'DEA'),
                            ('DESS', 'DESS'),
                            ('AUTRE', 'Autre'),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),

        # etablissement.date_agrement / numero_agrement : colonnes déjà présentes.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='etablissement',
                    name='date_agrement',
                    field=models.DateField(blank=True, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='etablissement',
                    name='numero_agrement',
                    field=models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),

        # etudiant.nationalite / numero_cni / sexe : colonnes déjà présentes.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='etudiant',
                    name='nationalite',
                    field=models.CharField(blank=True, default='Camerounaise', max_length=30, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='etudiant',
                    name='numero_cni',
                    field=models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='etudiant',
                    name='sexe',
                    field=models.CharField(
                        blank=True,
                        choices=[('M', 'Masculin'), ('F', 'Féminin')],
                        max_length=1,
                        null=True,
                    ),
                ),
            ],
        ),

        # classe : contraintes FK déjà présentes avec les noms Django générés.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='classe',
                    name='code_bat',
                    field=models.ForeignKey(
                        blank=True, db_column='code_bat', null=True,
                        on_delete=django.db.models.deletion.SET_NULL, to='api.batiment',
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='classe',
                    name='code_niveau',
                    field=models.ForeignKey(
                        blank=True, db_column='code_niveau', null=True,
                        on_delete=django.db.models.deletion.SET_NULL, to='api.niveau',
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='classe',
                    name='code_salle',
                    field=models.ForeignKey(
                        blank=True, db_column='code_salle', null=True,
                        on_delete=django.db.models.deletion.SET_NULL, to='api.salle',
                    ),
                ),
            ],
        ),

        # cours.mle_ens : contrainte FK déjà présente.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='cours',
                    name='mle_ens',
                    field=models.ForeignKey(
                        blank=True, db_column='mle_ens', null=True,
                        on_delete=django.db.models.deletion.SET_NULL, to='api.enseignant',
                    ),
                ),
            ],
        ),

        # document_genere : contraintes FK déjà présentes.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='documentgenere',
                    name='code_annee',
                    field=models.ForeignKey(
                        blank=True, db_column='code_annee', null=True,
                        on_delete=django.db.models.deletion.SET_NULL, to='api.annee',
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='documentgenere',
                    name='code_classe',
                    field=models.ForeignKey(
                        blank=True, db_column='code_classe', null=True,
                        on_delete=django.db.models.deletion.SET_NULL, to='api.classe',
                    ),
                ),
            ],
        ),

        # evaluation.code_type_eval : contrainte FK déjà présente.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='evaluation',
                    name='code_type_eval',
                    field=models.ForeignKey(
                        db_column='code_type_eval',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='api.typeevaluation',
                    ),
                ),
            ],
        ),

        # niveau.code_pension : contrainte FK déjà présente.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='niveau',
                    name='code_pension',
                    field=models.ForeignKey(
                        blank=True, db_column='code_pension', null=True,
                        on_delete=django.db.models.deletion.SET_NULL, to='api.pension',
                    ),
                ),
            ],
        ),

        # planning.code_annee : contrainte FK déjà présente.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='planning',
                    name='code_annee',
                    field=models.ForeignKey(
                        db_column='code_annee',
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='api.annee',
                    ),
                ),
            ],
        ),

        # rapport_statistique : contraintes FK déjà présentes.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='rapportstatistique',
                    name='code_classe',
                    field=models.ForeignKey(
                        blank=True, db_column='code_classe', null=True,
                        on_delete=django.db.models.deletion.SET_NULL, to='api.classe',
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='rapportstatistique',
                    name='code_dep',
                    field=models.ForeignKey(
                        blank=True, db_column='code_dep', null=True,
                        on_delete=django.db.models.deletion.SET_NULL, to='api.departement',
                    ),
                ),
            ],
        ),

        # inscription : contrainte unique déjà présente en base.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='inscription',
                    unique_together={('mle_etudiant', 'code_annee')},
                ),
            ],
        ),

        # ── Opérations normales (exécutées en base) ───────────────────────────

        migrations.AlterField(
            model_name='annee',
            name='statut',
            field=models.CharField(
                blank=True,
                choices=[('EN COURS', 'En cours'), ('CLOTUREE', 'Clôturée'), ('PLANIFIEE', 'Planifiée')],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='decision',
            name='resultat',
            field=models.CharField(
                choices=[
                    ('ADMIS', 'Admis(e)'),
                    ('AJOURNE', 'Ajourné(e)'),
                    ('REDOUBLE', 'Redoublant(e)'),
                    ('EXCLU', 'Exclu(e)'),
                    ('EN_ATTENTE', 'En attente de délibération'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='statut',
            field=models.CharField(
                blank=True,
                choices=[
                    ('PERMANENT', 'Permanent'),
                    ('VACATAIRE', 'Vacataire'),
                    ('CONTRACTUEL', 'Contractuel'),
                    ('FONCTIONNAIRE', 'Fonctionnaire'),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_naiss',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='type_examen',
            field=models.CharField(
                choices=[
                    ('ECRIT', 'Écrit'),
                    ('ORAL', 'Oral'),
                    ('PRATIQUE', 'Pratique'),
                    ('TP', 'Travaux Pratiques'),
                    ('RATTRAPAGE', 'Session de rattrapage'),
                ],
                default='ECRIT',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_emission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(
                choices=[
                    ('EN_ATTENTE', 'En attente'),
                    ('PARTIELLEMENT_PAYEE', 'Partiellement payée'),
                    ('SOLDEE', 'Soldée'),
                    ('ANNULEE', 'Annulée'),
                ],
                default='EN_ATTENTE',
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name='fichenotes',
            name='statut',
            field=models.CharField(
                choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('IMPORTE', 'Importé')],
                default='BROUILLON',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='mention',
            name='note_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mention',
            name='note_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(
                blank=True,
                choices=[
                    ('EN_ATTENTE', 'En attente'),
                    ('PAYE', 'Payé'),
                    ('ANNULE', 'Annulé'),
                    ('REMBOURSE', 'Remboursé'),
                ],
                default='EN_ATTENTE',
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='seance',
            name='statut',
            field=models.CharField(
                choices=[('TENU', 'Tenu'), ('ANNULE', 'Annulé'), ('REPORTE', 'Reporté')],
                default='TENU',
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name='stage',
            name='statut',
            field=models.CharField(
                choices=[
                    ('EN_COURS', 'En cours'),
                    ('TERMINE', 'Terminé'),
                    ('VALIDE', 'Validé'),
                    ('ANNULE', 'Annulé'),
                ],
                default='EN_COURS',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type_stage',
            field=models.CharField(
                choices=[
                    ('OBSERVATION', "Stage d'observation"),
                    ('IMMERSION', "Stage d'immersion"),
                    ('PFE', "Projet de Fin d'Études"),
                    ('ACADEMIQUE', 'Stage académique'),
                    ('PROFESSIONNEL', 'Stage professionnel'),
                ],
                default='OBSERVATION',
                max_length=30,
            ),
        ),
        # type_evaluation: colonnes déjà renommées en snake_case en base.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='typeevaluation',
                    name='code_type_eval',
                    field=models.AutoField(db_column='code_type_eval', primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='typeevaluation',
                    name='obs_type_eval',
                    field=models.CharField(blank=True, db_column='obs_type_eval', max_length=45, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(
                choices=[
                    ('ADMIN', 'Administrateur'),
                    ('SCOLARITE', 'Scolarité'),
                    ('ENSEIGNANT', 'Enseignant'),
                    ('COMPTABLE', 'Comptable'),
                    ('ETUDIANT', 'Étudiant'),
                    ('DIRECTION', 'Direction'),
                ],
                default='ETUDIANT',
                max_length=20,
            ),
        ),
        # Créer faculte avec la bonne collation (utf8mb4_unicode_ci) pour
        # rester compatible avec les tables existantes (MySQL 8 utilise
        # utf8mb4_0900_ai_ci par défaut, ce qui empêche les clés étrangères).
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE faculte (
                            code_faculte varchar(10) NOT NULL
                                COLLATE utf8mb4_unicode_ci,
                            lib_faculte  varchar(100) NOT NULL
                                COLLATE utf8mb4_unicode_ci,
                            obs_faculte  varchar(100) NULL
                                COLLATE utf8mb4_unicode_ci,
                            code_etab    varchar(10) NOT NULL
                                COLLATE utf8mb4_unicode_ci,
                            PRIMARY KEY (code_faculte),
                            CONSTRAINT fk_faculte_etab
                                FOREIGN KEY (code_etab)
                                REFERENCES etablissement (code_etab)
                        ) ENGINE=InnoDB
                          DEFAULT CHARSET=utf8mb4
                          COLLATE=utf8mb4_unicode_ci
                    """,
                    reverse_sql="DROP TABLE IF EXISTS faculte",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Faculte',
                    fields=[
                        ('code_faculte', models.CharField(max_length=10, primary_key=True, serialize=False)),
                        ('lib_faculte', models.CharField(max_length=100)),
                        ('obs_faculte', models.CharField(blank=True, max_length=100, null=True)),
                        ('code_etab', models.ForeignKey(
                            db_column='code_etab',
                            on_delete=django.db.models.deletion.RESTRICT,
                            to='api.etablissement',
                        )),
                    ],
                    options={
                        'db_table': 'faculte',
                    },
                ),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='code_faculte',
            field=models.ForeignKey(
                blank=True, db_column='code_faculte', null=True,
                on_delete=django.db.models.deletion.SET_NULL, to='api.faculte',
            ),
        ),
    ]
