# Generated by Django 5.2.12 on 2026-08-10 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_typeevaluation_ponderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='utilisateur',
            field=models.OneToOneField(blank=True, db_column='utilisateur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignant', to='api.utilisateur'),
        ),
    ]
