# Generated by Django 5.2.12 on 2026-08-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_enseignant_utilisateur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['-code_annee', 'code_classe', 'code_matiere']},
        ),
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['-date_examen']},
        ),
        migrations.AlterModelOptions(
            name='fichenotes',
            options={'ordering': ['-date_evaluation']},
        ),
    ]
