# Generated by Django 5.2.12 on 2026-04-27 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_restructure_cours_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='numero_cni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='credits',
            field=models.PositiveIntegerField(default=0, help_text='Crédits LMD attribués à cette matière'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='quota_horaire',
            field=models.PositiveIntegerField(default=20, help_text="Nombre total d'heures prévu sur le semestre (ex: 20h, 30h, 45h)"),
        ),
        migrations.AlterField(
            model_name='planning',
            name='code_cours',
            field=models.ForeignKey(help_text='Attribution (matière + classe + semestre) concernée', on_delete=django.db.models.deletion.CASCADE, to='api.cours'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='date_debut',
            field=models.DateField(blank=True, help_text='Premier jour de la semaine intensive (ex: 2026-02-03)', null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Dernier jour de la semaine intensive (ex: 2026-02-07)', null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='h_debut',
            field=models.TimeField(help_text='Heure de début (ex : 08:00)'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='h_fin',
            field=models.TimeField(help_text='Heure de fin   (ex : 10:00)'),
        ),
    ]
