# Generated by Django 5.2.12 on 2026-08-10 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cours_options_alter_examen_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('code_epreuve', models.AutoField(primary_key=True, serialize=False)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='epreuves/')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='BROUILLON', max_length=20)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_validation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(blank=True, db_column='etablissement_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.etablissement')),
                ('examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='epreuve', to='api.examen')),
                ('soumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.enseignant')),
                ('valide_par', models.ForeignKey(blank=True, db_column='valide_par_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.utilisateur')),
            ],
            options={
                'db_table': 'epreuve',
                'ordering': ['-created_at'],
            },
        ),
    ]
