# Generated by Django 5.2.12 on 2026-08-10 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_epreuve'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(blank=True, choices=[('PROFESSEUR', 'Professeur Titulaire'), ('MAITRE_CONF', 'Maître de Conférences'), ('CHARGE_COURS', 'Chargé de Cours'), ('ASSISTANT', 'Assistant'), ('VACATAIRE', 'Vacataire')], help_text='Grade académique CAMES — principalement utilisé dans le supérieur.', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='typeevaluation',
            name='remplace',
            field=models.ForeignKey(blank=True, db_column='remplace_id', help_text="Type d'évaluation remplacé par celui-ci quand une note existe (ex: Rattrapage remplace Session normale).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplace_par', to='api.typeevaluation'),
        ),
    ]
