# Generated by Django 5.2.12 on 2026-04-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_enseignant_add_sexe_cni'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='groupes',
            field=models.CharField(blank=True, help_text='Groupes/spécialités concernés pour les cours tronc commun en amphi (ex: GI1, GL1, IA1)', max_length=200, null=True),
        ),
    ]
