# Generated by Django 5.2.12 on 2026-05-07 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cours_add_groupes'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('SCOLARITE', 'Scolarité'), ('INSCRIPTION', 'Inscription')], default='SCOLARITE', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='code_tranche',
            field=models.ForeignKey(blank=True, db_column='code_tranche', null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.tranche'),
        ),
    ]
