# Generated by Django 5.2.12 on 2026-08-10 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_enseignant_grade_typeevaluation_remplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementSalaire',
            fields=[
                ('code_paiement_salaire', models.AutoField(primary_key=True, serialize=False)),
                ('mois_paie', models.DateField(help_text='Premier jour du mois concerné (ex : 2026-06-01).')),
                ('montant', models.PositiveIntegerField(default=0)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire'), ('MOBILE', 'Mobile Money'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=20)),
                ('ref_paiement', models.CharField(blank=True, default='', max_length=100)),
                ('observation', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(blank=True, db_column='mle_ens', null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.enseignant')),
                ('etablissement', models.ForeignKey(blank=True, db_column='etablissement_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.etablissement')),
                ('personnel', models.ForeignKey(blank=True, db_column='mle_personnel', null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.personnel')),
            ],
            options={
                'db_table': 'paiement_salaire',
                'ordering': ['-mois_paie', '-created_at'],
            },
        ),
    ]
