# Generated by Django 5.2.12 on 2026-05-22 15:10
# Qualification table already has (code_matiere, mle_ens) as composite PK in MySQL
# with no 'id' column — wrapped in SeparateDatabaseAndState so Django state matches reality.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_etudiant_matricule_varchar20'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='qualification',
                    unique_together=set(),
                ),
                migrations.AddField(
                    model_name='qualification',
                    name='pk',
                    field=models.CompositePrimaryKey('code_matiere_id', 'mle_ens_id', blank=True, editable=False, primary_key=True, serialize=False),
                ),
                migrations.RemoveField(
                    model_name='qualification',
                    name='id',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('SCOLARITE', 'Scolarité'), ('INSCRIPTION', 'Inscription'), ('EXAMEN_BTS', "Frais d'examen BTS"), ('SOUTENANCE_BTS', 'Frais de soutenance BTS'), ('SOUTENANCE_LICENCE', 'Frais de soutenance Licence'), ('SOUTENANCE_MASTER', 'Frais de soutenance Master')], default='SCOLARITE', max_length=20),
        ),
    ]
