# Generated by Django 5.2.12 on 2026-08-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_evaluation_appreciation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('ADMIN', 'Administrateur'), ('SCOLARITE', 'Scolarité'), ('ENSEIGNANT', 'Enseignant'), ('COMPTABLE', 'Comptable'), ('ETUDIANT', 'Étudiant'), ('DIRECTION', 'Direction'), ('CENSEUR', 'Censeur / Préfet des études'), ('SURVEILLANT_GENERAL', 'Surveillant Général'), ('APEE', 'Représentant APEE')], default='ETUDIANT', max_length=20),
        ),
    ]
