# Generated by Django 5.2.12 on 2026-05-22 15:14
# unite_enseignement table already has (code_matiere, code_classe) as composite PK — no 'id' column.
# SeparateDatabaseAndState: update Django state only, no DB operations.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_qualification_unique_together_qualification_pk_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='uniteenseignement',
                    unique_together=set(),
                ),
                migrations.AddField(
                    model_name='uniteenseignement',
                    name='pk',
                    field=models.CompositePrimaryKey('code_matiere_id', 'code_classe_id', blank=True, editable=False, primary_key=True, serialize=False),
                ),
                migrations.RemoveField(
                    model_name='uniteenseignement',
                    name='id',
                ),
            ],
        ),
    ]
