# Generated by Django 5.2.12 on 2026-08-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='organisme',
            field=models.CharField(choices=[('INTERNE', "Examen interne à l'établissement"), ('MINESEC', 'MINESEC — Direction des Examens, Concours et Certification'), ('MINEDUB', 'MINEDUB'), ('OBC', 'Office du Baccalauréat du Cameroun'), ('GCE_BOARD', 'Cameroon GCE Board')], default='INTERNE', max_length=15),
        ),
        migrations.AddField(
            model_name='examen',
            name='type_officiel',
            field=models.CharField(blank=True, choices=[('CEP', "CEP — Certificat d'Études Primaires"), ('FSLC', 'FSLC — First School Leaving Certificate'), ('BEPC', "BEPC — Brevet d'Études du Premier Cycle"), ('GCE_O_LEVEL', 'GCE Ordinary Level'), ('PROBATOIRE', 'Probatoire'), ('BAC', 'Baccalauréat'), ('GCE_A_LEVEL', 'GCE Advanced Level'), ('CAP', "CAP — Certificat d'Aptitude Professionnelle"), ('BT', 'BT — Brevet de Technicien'), ('BP', 'BP — Brevet Professionnel')], help_text='Diplôme national auquel appartient cet examen (BEPC, Bac, GCE…) — vide si examen interne.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='type_diplome',
            field=models.CharField(blank=True, choices=[('CEP', "CEP — Certificat d'Études Primaires"), ('FSLC', 'FSLC — First School Leaving Certificate'), ('BEPC', "BEPC — Brevet d'Études du Premier Cycle"), ('GCE_O_LEVEL', 'GCE Ordinary Level'), ('PROBATOIRE', 'Probatoire'), ('BAC', 'Baccalauréat'), ('GCE_A_LEVEL', 'GCE Advanced Level'), ('CAP', "CAP — Certificat d'Aptitude Professionnelle"), ('BT', 'BT — Brevet de Technicien'), ('BP', 'BP — Brevet Professionnel'), ('LICENCE', 'Licence'), ('LICENCE_PRO', 'Licence Professionnelle'), ('MASTER', 'Master'), ('MASTER_PRO', 'Master Professionnel'), ('DOCTORAT', 'Doctorat / PhD'), ('BTS', 'Brevet de Technicien Supérieur'), ('HND', 'Higher National Diploma'), ('DUT', 'Diplôme Universitaire de Technologie'), ('INGENIEUR', "Diplôme d'Ingénieur"), ('DEA', 'DEA'), ('DESS', 'DESS'), ('AUTRE', 'Autre')], max_length=20, null=True),
        ),
    ]
