# Generated by Django 5.2.12 on 2026-08-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_examen_organisme_examen_type_officiel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('SCOLARITE', 'Scolarité'), ('INSCRIPTION', 'Inscription'), ('EXAMEN_BTS', "Frais d'examen BTS"), ('SOUTENANCE_BTS', 'Frais de soutenance BTS'), ('SOUTENANCE_LICENCE', 'Frais de soutenance Licence'), ('SOUTENANCE_MASTER', 'Frais de soutenance Master'), ('APEE', "Frais APEE (Association des Parents d'Élèves et Enseignants)"), ('EXAMEN_OFFICIEL', "Frais d'examen officiel (État)")], default='SCOLARITE', max_length=20),
        ),
    ]
