# Generated by Django 5.2.12 on 2026-05-25 08:28
# matiere.code_matiere already VARCHAR(20) in DB; FK columns still VARCHAR(10).
# RunSQL aligns all FK columns; SeparateDatabaseAndState updates state only for matiere.
# foreign_key_checks disabled during ALTERs to avoid MySQL 3780 (charset/size mismatch
# between referencing and referenced columns while they are being updated in sequence).

from django.db import migrations, models

FK_TABLES = [
    'cours', 'evaluation', 'examen', 'fiche_notes',
    'qualification', 'rapport_cours', 'seance', 'unite_enseignement',
]

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_uniteenseignement_unique_together_and_more'),
    ]

    operations = [
        # ── State only for matiere (DB already correct) ──────────────────────
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='matiere',
                    name='code_matiere',
                    field=models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='matiere',
                    name='lib_matiere',
                    field=models.CharField(max_length=60),
                ),
            ],
        ),
        # ── Disable FK checks so MySQL allows mismatched-size ALTERs ─────────
        migrations.RunSQL(
            sql="SET foreign_key_checks = 0",
            reverse_sql="SET foreign_key_checks = 1",
        ),
        # ── Align FK columns in dependent tables ─────────────────────────────
        *[
            migrations.RunSQL(
                sql=f"ALTER TABLE `{t}` MODIFY COLUMN `code_matiere` VARCHAR(20) NOT NULL",
                reverse_sql=f"ALTER TABLE `{t}` MODIFY COLUMN `code_matiere` VARCHAR(10) NOT NULL",
            )
            for t in FK_TABLES
        ],
        # ── Re-enable FK checks ───────────────────────────────────────────────
        migrations.RunSQL(
            sql="SET foreign_key_checks = 1",
            reverse_sql="SET foreign_key_checks = 0",
        ),
    ]
