# Generated by Django 5.2.12 on 2026-08-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_paiement_type_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='systeme',
            field=models.CharField(blank=True, choices=[('FRANCOPHONE', 'Francophone'), ('ANGLOPHONE', 'Anglophone')], max_length=15, null=True),
        ),
    ]
