# Generated by Django 5.2.12 on 2026-05-25 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_matiere_code_matiere_alter_matiere_lib_matiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_etab', models.CharField(max_length=20, unique=True)),
                ('afficher_rang', models.BooleanField(default=True)),
                ('afficher_mention', models.BooleanField(default=True)),
                ('afficher_coef', models.BooleanField(default=True)),
                ('afficher_apprec', models.BooleanField(default=True)),
                ('note_eliminatoire', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('moyenne_passage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('bareme_defaut', models.PositiveSmallIntegerField(default=20)),
                ('pied_page_bulletin', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'config_bulletin',
            },
        ),
        migrations.CreateModel(
            name='NiveauScolaire',
            fields=[
                ('code_niveau', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lib_niveau', models.CharField(max_length=100)),
                ('lib_en', models.CharField(blank=True, max_length=100)),
                ('type_etab', models.CharField(max_length=20)),
                ('systeme', models.CharField(default='FRANCOPHONE', max_length=15)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'niveau_scolaire',
                'ordering': ['type_etab', 'ordre'],
            },
        ),
        migrations.AddField(
            model_name='etablissement',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='directeur',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='ministere_tutelle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='numero_autorisation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='region',
            field=models.CharField(blank=True, choices=[('ADAMAOUA', 'Adamaoua'), ('CENTRE', 'Centre'), ('EST', 'Est'), ('EXTREME_NORD', 'Extrême-Nord'), ('LITTORAL', 'Littoral'), ('NORD', 'Nord'), ('NORD_OUEST', 'Nord-Ouest'), ('OUEST', 'Ouest'), ('SUD', 'Sud'), ('SUD_OUEST', 'Sud-Ouest')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='sigle',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='site_web',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='statut',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVE_LAIQUE', 'Privé laïque'), ('CONFESSIONNEL', 'Confessionnel')], default='PRIVE_LAIQUE', max_length=20),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='systeme',
            field=models.CharField(choices=[('FRANCOPHONE', 'Francophone'), ('ANGLOPHONE', 'Anglophone'), ('BILINGUE', 'Bilingue')], default='FRANCOPHONE', max_length=15),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='type_etab',
            field=models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire'), ('SUPERIEUR', 'Supérieur')], default='SUPERIEUR', max_length=20),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='code_type',
            field=models.ForeignKey(blank=True, db_column='code_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typeetab'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='lib_etab',
            field=models.CharField(max_length=200),
        ),
    ]
