# Generated by Django 5.2.12 on 2026-05-25 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_multi_etab_niveaux_scolaires'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE classe
                ADD COLUMN niveau_scolaire VARCHAR(20)
                    CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci
                    NULL DEFAULT NULL;
                ALTER TABLE classe
                ADD CONSTRAINT classe_niveau_scolaire_fk
                    FOREIGN KEY (niveau_scolaire)
                    REFERENCES niveau_scolaire(code_niveau)
                    ON DELETE SET NULL;
            """,
            reverse_sql="""
                ALTER TABLE classe DROP FOREIGN KEY classe_niveau_scolaire_fk;
                ALTER TABLE classe DROP COLUMN niveau_scolaire;
            """,
            state_operations=[
                migrations.AddField(
                    model_name='classe',
                    name='niveau_scolaire',
                    field=models.ForeignKey(
                        blank=True, db_column='niveau_scolaire', null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='classes', to='api.niveauscolaire'
                    ),
                ),
            ],
        ),
    ]
