# Generated by Django 5.2.12 on 2026-08-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_classe_systeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='periode',
            name='type_periode',
            field=models.CharField(choices=[('ORDINAIRE', 'Séquence / trimestre ordinaire'), ('EXAMENS_OFFICIELS', "Période d'examens officiels")], default='ORDINAIRE', max_length=20),
        ),
    ]
