# Generated by Django 5.2.12 on 2026-08-14 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_periode_type_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplome',
            name='etablissement_tutelle',
            field=models.ForeignKey(blank=True, help_text='Établissement de tutelle académique ayant co-signé ce diplôme (IPES non homologué).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.etablissement'),
        ),
        migrations.AddField(
            model_name='diplome',
            name='signe_par_tutelle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='etablissement_tutelle',
            field=models.ForeignKey(blank=True, help_text="Établissement homologué garantissant la qualité de l'enseignement tant que celui-ci n'est pas lui-même homologué.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements_sous_tutelle', to='api.etablissement'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='statut_agrement',
            field=models.CharField(blank=True, choices=[('DECLARE', 'Déclaré'), ('CREE', 'Créé (autorisation de création obtenue)'), ('OUVERT', "Ouvert (autorisation d'ouverture obtenue)"), ('HOMOLOGUE', 'Homologué (habilité à délivrer directement des diplômes nationaux)')], help_text="Cycle de vie d'agrément — pertinent surtout pour un IPES (supérieur privé) non homologué.", max_length=20, null=True),
        ),
    ]
