# Generated by Django 5.2.12 on 2026-08-31 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_diplome_etablissement_tutelle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportstatistique',
            name='code_faculte',
            field=models.ForeignKey(blank=True, db_column='code_faculte', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.faculte'),
        ),
        migrations.AddField(
            model_name='rapportstatistique',
            name='code_sp',
            field=models.ForeignKey(blank=True, db_column='code_sp', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.specialite'),
        ),
    ]
