# Generated by Django 5.2.12 on 2026-08-31 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rapportstatistique_code_faculte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportAssiduite',
            fields=[
                ('code_rapport_assiduite', models.AutoField(primary_key=True, serialize=False)),
                ('periode_debut', models.DateField(blank=True, null=True)),
                ('periode_fin', models.DateField(blank=True, null=True)),
                ('nb_etudiants', models.PositiveIntegerField(default=0)),
                ('nb_seances', models.PositiveIntegerField(default=0)),
                ('nb_controles', models.PositiveIntegerField(default=0)),
                ('nb_absences', models.PositiveIntegerField(default=0)),
                ('nb_absences_injustifiees', models.PositiveIntegerField(default=0)),
                ('genere_par', models.CharField(blank=True, max_length=50, null=True)),
                ('genere_le', models.DateTimeField(auto_now_add=True)),
                ('code_annee', models.ForeignKey(db_column='code_annee', on_delete=django.db.models.deletion.RESTRICT, to='api.annee')),
                ('code_classe', models.ForeignKey(blank=True, db_column='code_classe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.classe')),
                ('code_dep', models.ForeignKey(blank=True, db_column='code_dep', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.departement')),
                ('code_faculte', models.ForeignKey(blank=True, db_column='code_faculte', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.faculte')),
                ('code_periode', models.ForeignKey(blank=True, db_column='code_periode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.periode')),
                ('code_sp', models.ForeignKey(blank=True, db_column='code_sp', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.specialite')),
                ('etablissement', models.ForeignKey(blank=True, db_column='etablissement_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.etablissement')),
            ],
            options={
                'db_table': 'rapport_assiduite',
                'ordering': ['-genere_le'],
            },
        ),
    ]
